name: Build
on:
  push:
    branches:
      - main
  pull_request:
    # TODO: this should run for every pr
    branches:
      - main
      - feat/rust-bindings
      - ci/rust-wheels
jobs:
  query-engine:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Build Python package
        working-directory: src/query-engine
        run: maturin build --release --no-sdist --out wheelhouse --strip --interpreter python${{matrix.python_version}}

      - uses: actions/upload-artifact@v2
        with:
          path: ./src/query-engine/wheelhouse/*.whl
