name: Release Query Engine
# TODO: on: workflow_dispatch
on:
  push:
    branches:
      - main
  pull_request:
    # TODO: this should run for every pr
    branches:
      - main
      - feat/rust-bindings
      - ci/rust-wheels
jobs:
  build-query-engine:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Build Query Engine Wheels
        working-directory: src/query-engine
        run: maturin build --release --no-sdist --out wheelhouse --strip --interpreter python${{matrix.python_version}}

      - uses: actions/upload-artifact@v2
        with:
          path: ./src/query-engine/wheelhouse/*.whl

  release-query-engine:
    needs: build-query-engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Test
        run: |
          ls -a .
